name: launch-test

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4

      - name: install
        run: npm install

      - name: run test
        run: npm run test
