name: launch-test

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v4
      - name: install jest
        run: npm install jest

      - name: run test
        run: npm test
